// Setup script for sponsored fees and reserves tutorials

import fs from 'fs'
import { fileURLToPath } from 'url'
import { Client, MPTokenIssuanceCreateFlags } from 'xrpl'

export async function setup() {
  const client = new Client('wss://s.devnet.rippletest.net:51233')
  await client.connect()

  process.stdout.write('Setting up tutorial: 0/2\r')

  // Create and fund the MPT issuer
  const { wallet: issuer } = await client.fundWallet()

  process.stdout.write('Setting up tutorial: 1/2\r')

  // Create the MPT issuance the tutorials authorize with sponsorship
  const mptIssuanceCreateTx = {
    TransactionType: 'MPTokenIssuanceCreate',
    Account: issuer.address,
    MaximumAmount: '1000000000000',
    AssetScale: 2,
    TransferFee: 0,
    Flags:
      MPTokenIssuanceCreateFlags.tfMPTCanTransfer |
      MPTokenIssuanceCreateFlags.tfMPTCanLock
  }
  const response = await client.submitAndWait(mptIssuanceCreateTx, {
    wallet: issuer,
    autofill: true
  })
  if (response.result.meta.TransactionResult !== 'tesSUCCESS') {
    const resultCode = response.result.meta.TransactionResult
    console.error('Error creating MPT issuance:', resultCode)
    await client.disconnect()
    process.exit(1)
  }

  const mptID = response.result.meta.mpt_issuance_id

  process.stdout.write('Setting up tutorial: 2/2\r')

  // Write the data the tutorials need
  const setupData = {
    description:
      'This file is auto-generated by sponsoredFeesAndReservesSetup.js. It stores XRPL account info for use in sponsored fees and reserves tutorials.',
    issuer: {
      address: issuer.address,
      seed: issuer.seed
    },
    mptID
  }

  fs.writeFileSync(
    'sponsoredFeesAndReservesSetup.json',
    JSON.stringify(setupData, null, 2)
  )

  await client.disconnect()
}

// Allow running this file directly: `node sponsoredFeesAndReservesSetup.js`
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await setup()
}
