#!/usr/bin/env python
import json
import sys

from xrpl.clients import JsonRpcClient
from xrpl.models.transactions import PermissionedDomainSet
from xrpl.models.transactions.deposit_preauth import Credential
from xrpl.transaction import submit_and_wait
from xrpl.utils import str_to_hex
from xrpl.wallet import generate_faucet_wallet

# Get issuer wallet and define constants ---------------------------------------
client = JsonRpcClient("https://s.altnet.rippletest.net:51234")
wallet = generate_faucet_wallet(client, debug=True)

issuer_address = wallet.address # Can also use a different credential issuer
credential_type = str_to_hex("my-credential")

# Create a domain --------------------------------------------------------------
p_domain_set = PermissionedDomainSet(
    account=wallet.address,
    accepted_credentials=[
        Credential(
            issuer=issuer_address,
            credential_type=credential_type
        )
    ]
)
print("Submitting transaction", p_domain_set)
pds_response = submit_and_wait(p_domain_set, client=client, wallet=wallet)
if pds_response.status != "success":
    print("Transaction submission failed:", pds_response)
    sys.exit(1)
print(json.dumps(pds_response.result, indent=2))
result_code = pds_response.result["meta"]["TransactionResult"]
if result_code != "tesSUCCESS":
    print("Transaction failed with result code", result_code)
    sys.exit(2)
print("Successfully created permissioned domain.")

# Find Domain ID in metadata ---------------------------------------------------
# Look for a created ledger entry of type PermissionedDomain and get 
# its ledger entry ID from the AffectedNodes part of the metadata.
#
# Note, an alternative way to get the Domain ID is to calculate it as the
# SHA-512Half of the PermissionedDomain space key, owner's account ID, and the
# sequence number of the transaction that created it.

domain_id = None
for modified_node in pds_response.result["meta"]["AffectedNodes"]:
    if "CreatedNode" in modified_node.keys():
        if modified_node["CreatedNode"]["LedgerEntryType"] == "PermissionedDomain":
            domain_id = modified_node["CreatedNode"]["LedgerIndex"]
            break
if not domain_id:
    print("Couldn't find a created Permissioned Domain in transaction metadata."
          " This is not typical.")
    sys.exit(3)
print("Domain ID of created domain:", domain_id)

# Save config for other scripts ------------------------------------------------
config_data = {
    "description": "This file is auto-generated by create_domain.py. "
        "It stores account and domain info for the other tutorial scripts.",
    "owner": {"address": wallet.address, "seed": wallet.seed},
    "issuer_address": issuer_address,
    "domain_id": domain_id,
}
with open("setup.json", "w") as f:
    json.dump(config_data, f, indent=2)
