// Setup script for cross-currency payment tutorial
import xrpl from 'xrpl'
import fs from 'fs'

const WSS_URL = 'wss://s.altnet.rippletest.net:51233'
const CURRENCY = 'USD'

const client = new xrpl.Client(WSS_URL)
await client.connect()

// Fund the four wallets the tutorial needs
process.stdout.write('Setting up tutorial: 1/5\r')
const [
  { wallet: issuer },
  { wallet: marketMaker },
  { wallet: sender },
  { wallet: receiver }
] = await Promise.all([
  client.fundWallet(),
  client.fundWallet(),
  client.fundWallet(),
  client.fundWallet()
])

// Enable rippling so the issuer's USD can move between holders
process.stdout.write('Setting up tutorial: 2/5\r')
await client.submitAndWait({
  TransactionType: 'AccountSet',
  Account: issuer.address,
  SetFlag: 8 // asfDefaultRipple
}, { wallet: issuer, autofill: true })

// Market maker and receiver trust the issuer's USD
process.stdout.write('Setting up tutorial: 3/5\r')
await Promise.all([
  client.submitAndWait({
    TransactionType: 'TrustSet',
    Account: marketMaker.address,
    LimitAmount: { currency: CURRENCY, issuer: issuer.address, value: '1000000' }
  }, { wallet: marketMaker, autofill: true }),
  client.submitAndWait({
    TransactionType: 'TrustSet',
    Account: receiver.address,
    LimitAmount: { currency: CURRENCY, issuer: issuer.address, value: '1000000' }
  }, { wallet: receiver, autofill: true })
])

// Issue USD to the market maker so it has inventory to sell
process.stdout.write('Setting up tutorial: 4/5\r')
await client.submitAndWait({
  TransactionType: 'Payment',
  Account: issuer.address,
  Destination: marketMaker.address,
  Amount: { currency: CURRENCY, issuer: issuer.address, value: '100000' }
}, { wallet: issuer, autofill: true })

// Post an offer providing XRP -> USD liquidity (4 USD per XRP)
process.stdout.write('Setting up tutorial: 5/5\r')
await client.submitAndWait({
  TransactionType: 'OfferCreate',
  Account: marketMaker.address,
  TakerGets: { currency: CURRENCY, issuer: issuer.address, value: '10000' },
  TakerPays: xrpl.xrpToDrops('2500')
}, { wallet: marketMaker, autofill: true })

const setupData = {
  description: 'Auto-generated by crossCurrencySetup.js. Stores XRPL account info for the cross-currency payment tutorial.',
  issuerAddress: issuer.address,
  currency: CURRENCY,
  sender: { address: sender.address, seed: sender.seed },
  receiver: { address: receiver.address, seed: receiver.seed }
}
fs.writeFileSync('crossCurrencySetup.json', JSON.stringify(setupData, null, 2))

await client.disconnect()
