package main

import (
	"encoding/json"
	"fmt"
	"os"
	"time"

	"github.com/Peersyst/xrpl-go/pkg/crypto"
	"github.com/Peersyst/xrpl-go/xrpl/faucet"
	"github.com/Peersyst/xrpl-go/xrpl/queries/account"
	"github.com/Peersyst/xrpl-go/xrpl/queries/common"
	"github.com/Peersyst/xrpl-go/xrpl/rpc"
	rpctypes "github.com/Peersyst/xrpl-go/xrpl/rpc/types"
	"github.com/Peersyst/xrpl-go/xrpl/transaction"
	"github.com/Peersyst/xrpl-go/xrpl/transaction/types"
	"github.com/Peersyst/xrpl-go/xrpl/wallet"
)

const (
	currencyCode = "FOO"
	totalSteps   = 4
)

func main() {
	cfg, err := rpc.NewClientConfig(
		"https://s.altnet.rippletest.net:51234",
		rpc.WithFaucetProvider(faucet.NewTestnetFaucetProvider()),
	)
	if err != nil {
		panic(err)
	}
	client := rpc.NewClient(cfg)

	submitOpts := func(w *wallet.Wallet) *rpctypes.SubmitOptions {
		return &rpctypes.SubmitOptions{Autofill: true, Wallet: w}
	}

	step := 1

	// Fund issuer, sender, and receiver concurrently
	fmt.Printf("Setting up tutorial: %d/%d\r", step, totalSteps)
	step++

	ch := make(chan wallet.Wallet, 3)
	createAndFund := func() {
		w, err := wallet.New(crypto.ED25519())
		if err != nil {
			panic(err)
		}
		if err := client.FundWallet(&w); err != nil {
			panic(err)
		}
		// Poll until account is validated on ledger
		funded := false
		for range 20 {
			_, err := client.Request(&account.InfoRequest{
				Account:     w.GetAddress(),
				LedgerIndex: common.Validated,
			})
			if err == nil {
				funded = true
				break
			}
			time.Sleep(time.Second)
		}
		if !funded {
			panic("Issue funding account: " + w.GetAddress().String())
		}
		ch <- w
	}
	go createAndFund()
	go createAndFund()
	go createAndFund()
	issuer := <-ch
	sender := <-ch
	receiver := <-ch

	fmt.Printf("Setting up tutorial: %d/%d\r", step, totalSteps)
	step++

	accountSetTx := transaction.AccountSet{
		BaseTx: transaction.BaseTx{Account: issuer.ClassicAddress},
	}
	// Enable Default Ripple on the issuer
	accountSetTx.SetAsfDefaultRipple()

	flatAccountSet := accountSetTx.Flatten()
	accountSetResp, err := client.SubmitTxAndWait(flatAccountSet, submitOpts(&issuer))
	if err != nil {
		panic(err)
	}
	if accountSetResp.Meta.TransactionResult != "tesSUCCESS" {
		panic("AccountSet failed: " + accountSetResp.Meta.TransactionResult)
	}

	// Create sender trust line to issuer
	fmt.Printf("Setting up tutorial: %d/%d\r", step, totalSteps)
	step++

	trustSetTx := transaction.TrustSet{
		BaseTx: transaction.BaseTx{Account: sender.ClassicAddress},
		LimitAmount: types.IssuedCurrencyAmount{
			Currency: currencyCode,
			Issuer:   issuer.ClassicAddress,
			Value:    "1000000000",
		},
	}
	flatTrustSet := trustSetTx.Flatten()
	trustSetResp, err := client.SubmitTxAndWait(flatTrustSet, submitOpts(&sender))
	if err != nil {
		panic(err)
	}
	if trustSetResp.Meta.TransactionResult != "tesSUCCESS" {
		panic("TrustSet failed: " + trustSetResp.Meta.TransactionResult)
	}

	// Issuer sends sender tokens
	fmt.Printf("Setting up tutorial: %d/%d\r", step, totalSteps)

	seedTx := transaction.Payment{
		BaseTx:      transaction.BaseTx{Account: issuer.ClassicAddress},
		Destination: sender.ClassicAddress,
		Amount: types.IssuedCurrencyAmount{
			Currency: currencyCode,
			Issuer:   issuer.ClassicAddress,
			Value:    "1000",
		},
	}
	flatSeed := seedTx.Flatten()
	seedResp, err := client.SubmitTxAndWait(flatSeed, submitOpts(&issuer))
	if err != nil {
		panic(err)
	}
	if seedResp.Meta.TransactionResult != "tesSUCCESS" {
		panic("Issuer seed payment failed: " + seedResp.Meta.TransactionResult)
	}

	// Write setup data
	setupData := struct {
		Description string `json:"description"`
		Issuer      any    `json:"issuer"`
		Sender      any    `json:"sender"`
		Receiver    any    `json:"receiver"`
	}{
		Description: "This file is auto-generated by go/send-trust-line-token-setup/main.go. It stores XRPL account info for the send-a-trust-line-token tutorial.",
		Issuer: map[string]string{
			"address": issuer.ClassicAddress.String(),
			"seed":    issuer.Seed,
		},
		Sender: map[string]string{
			"address": sender.ClassicAddress.String(),
			"seed":    sender.Seed,
		},
		Receiver: map[string]string{
			"address": receiver.ClassicAddress.String(),
			"seed":    receiver.Seed,
		},
	}

	jsonData, err := json.MarshalIndent(setupData, "", "  ")
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile("send-trust-line-token-setup.json", jsonData, 0644); err != nil {
		panic(err)
	}
}
