import { readFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'

import react from '@vitejs/plugin-react'
import { defineConfig, type Plugin } from 'vite'

const require = createRequire(import.meta.url)

/**
 * The confidential-MPT proofs are generated by `@xrplf/mpt-crypto`, whose WASM
 * glue fetches `mpt_crypto.wasm` from a URL relative to its own chunk. Emit the
 * binary next to the built JS chunks so that fetch resolves in production.
 */
function copyMptCryptoWasm (): Plugin {
  return {
    name: 'copy-mpt-crypto-wasm',
    apply: 'build',
    generateBundle () {
      const wasmPath = join(
        dirname(require.resolve('@xrplf/mpt-crypto/wasm')),
        'mpt_crypto.wasm'
      )
      this.emitFile({
        type: 'asset',
        fileName: 'assets/mpt_crypto.wasm',
        source: readFileSync(wasmPath)
      })
    }
  }
}

export default defineConfig({
  plugins: [react(), copyMptCryptoWasm()],
  optimizeDeps: {
    // Pre-bundle the CommonJS xrpl build, but leave the ESM wasm wrapper
    // untouched so its import.meta.url-relative wasm fetch keeps working in dev.
    include: ['xrpl'],
    exclude: ['@xrplf/mpt-crypto']
  }
})
