package main

import (
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/Peersyst/xrpl-go/pkg/crypto"
	"github.com/Peersyst/xrpl-go/xrpl/faucet"
	"github.com/Peersyst/xrpl-go/xrpl/queries/account"
	"github.com/Peersyst/xrpl-go/xrpl/queries/common"
	"github.com/Peersyst/xrpl-go/xrpl/rpc"
	rpctypes "github.com/Peersyst/xrpl-go/xrpl/rpc/types"
	"github.com/Peersyst/xrpl-go/xrpl/transaction"
	"github.com/Peersyst/xrpl-go/xrpl/transaction/types"
	"github.com/Peersyst/xrpl-go/xrpl/wallet"
)

const totalSteps = 4

func main() {
	cfg, err := rpc.NewClientConfig(
		"https://s.altnet.rippletest.net:51234",
		rpc.WithFaucetProvider(faucet.NewTestnetFaucetProvider()),
	)
	if err != nil {
		panic(err)
	}
	client := rpc.NewClient(cfg)

	submitOpts := func(w *wallet.Wallet) *rpctypes.SubmitOptions {
		return &rpctypes.SubmitOptions{Autofill: true, Wallet: w}
	}

	step := 1

	// Fund issuer and sender concurrently
	fmt.Printf("Setting up tutorial: %d/%d\r", step, totalSteps)
	step++

	ch := make(chan wallet.Wallet, 2)
	createAndFund := func() {
		w, err := wallet.New(crypto.ED25519())
		if err != nil {
			panic(err)
		}
		if err := client.FundWallet(&w); err != nil {
			panic(err)
		}
		// Poll until account is validated on ledger
		funded := false
		for range 20 {
			_, err := client.Request(&account.InfoRequest{
				Account:     w.GetAddress(),
				LedgerIndex: common.Validated,
			})
			if err == nil {
				funded = true
				break
			}
			time.Sleep(time.Second)
		}
		if !funded {
			panic("Issue funding account: " + w.GetAddress().String())
		}
		ch <- w
	}
	go createAndFund()
	go createAndFund()
	issuer := <-ch
	sender := <-ch

	// Issue MPT with Can Transfer flag
	fmt.Printf("Setting up tutorial: %d/%d\r", step, totalSteps)
	step++

	// XLS-89 metadata. The Go SDK has no encode helper, so build the compact
	// short-key JSON and hex-encode it. json.Marshal sorts map keys, giving
	// deterministic output.
	metadata := map[string]string{
		"t":  "TUTO",
		"n":  "Tutorial Token",
		"d":  "Example MPT for the Send an MPT tutorial.",
		"i":  "https://example.org/tutorial-icon.png",
		"ac": "other",
		"in": "XRPL Tutorial Issuer",
	}
	metadataJSON, err := json.Marshal(metadata)
	if err != nil {
		panic(err)
	}
	metadataHex := strings.ToUpper(hex.EncodeToString(metadataJSON))

	assetScale := uint8(2)
	transferFee := uint16(0)
	maxAmount := types.XRPCurrencyAmount(1_000_000)
	issueTx := &transaction.MPTokenIssuanceCreate{
		BaseTx:          transaction.BaseTx{Account: issuer.ClassicAddress},
		AssetScale:      &assetScale,
		TransferFee:     &transferFee,
		MaximumAmount:   &maxAmount,
		MPTokenMetadata: &metadataHex,
	}
	issueTx.SetMPTCanTransferFlag()
	flatIssue := issueTx.Flatten()
	issueResp, err := client.SubmitTxAndWait(flatIssue, submitOpts(&issuer))
	if err != nil {
		panic(err)
	}
	if issueResp.Meta.TransactionResult != "tesSUCCESS" {
		panic("MPTokenIssuanceCreate failed: " + issueResp.Meta.TransactionResult)
	}
	if issueResp.Meta.MPTIssuanceID == nil {
		panic("MPTokenIssuanceCreate did not return an MPTIssuanceID")
	}
	mptIssuanceID := string(*issueResp.Meta.MPTIssuanceID)

	// Sender authorizes the MPT
	fmt.Printf("Setting up tutorial: %d/%d\r", step, totalSteps)
	step++

	authTx := &transaction.MPTokenAuthorize{
		BaseTx:            transaction.BaseTx{Account: sender.ClassicAddress},
		MPTokenIssuanceID: mptIssuanceID,
	}
	flatAuth := authTx.Flatten()
	authResp, err := client.SubmitTxAndWait(flatAuth, submitOpts(&sender))
	if err != nil {
		panic(err)
	}
	if authResp.Meta.TransactionResult != "tesSUCCESS" {
		panic("MPTokenAuthorize failed: " + authResp.Meta.TransactionResult)
	}

	// Issuer sends sender MPTs
	fmt.Printf("Setting up tutorial: %d/%d\r", step, totalSteps)

	seedTx := &transaction.Payment{
		BaseTx:      transaction.BaseTx{Account: issuer.ClassicAddress},
		Destination: sender.ClassicAddress,
		Amount: &types.MPTCurrencyAmount{
			MPTIssuanceID: mptIssuanceID,
			Value:         "500",
		},
	}
	flatSeed := seedTx.Flatten()
	seedResp, err := client.SubmitTxAndWait(flatSeed, submitOpts(&issuer))
	if err != nil {
		panic(err)
	}
	if seedResp.Meta.TransactionResult != "tesSUCCESS" {
		panic("Issuer seed payment failed: " + seedResp.Meta.TransactionResult)
	}

	// Write setup data
	setupData := struct {
		Description   string `json:"description"`
		Issuer        any    `json:"issuer"`
		Sender        any    `json:"sender"`
		MPTIssuanceID string `json:"mptIssuanceID"`
	}{
		Description: "This file is auto-generated by go/send-mpt-setup/main.go. It stores XRPL account info and the MPT issuance ID for the send-an-mpt tutorial.",
		Issuer: map[string]string{
			"address": issuer.ClassicAddress.String(),
			"seed":    issuer.Seed,
		},
		Sender: map[string]string{
			"address": sender.ClassicAddress.String(),
			"seed":    sender.Seed,
		},
		MPTIssuanceID: mptIssuanceID,
	}

	jsonData, err := json.MarshalIndent(setupData, "", "  ")
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile("send-mpt-setup.json", jsonData, 0644); err != nil {
		panic(err)
	}
}
