# Setup script for cross-currency payment tutorial
import asyncio
import json

from xrpl.asyncio.clients import AsyncWebsocketClient
from xrpl.asyncio.transaction import submit_and_wait
from xrpl.asyncio.wallet import generate_faucet_wallet
from xrpl.models.amounts import IssuedCurrencyAmount
from xrpl.models.transactions import (
    AccountSet,
    AccountSetAsfFlag,
    OfferCreate,
    Payment,
    TrustSet,
)
from xrpl.utils import xrp_to_drops

WSS_URL = "wss://s.altnet.rippletest.net:51233"
CURRENCY = "USD"


async def main():
    async with AsyncWebsocketClient(WSS_URL) as client:
        # Fund the four wallets the tutorial needs
        print("Setting up tutorial: 1/5", end="\r")
        issuer, market_maker, sender, receiver = await asyncio.gather(
            generate_faucet_wallet(client),
            generate_faucet_wallet(client),
            generate_faucet_wallet(client),
            generate_faucet_wallet(client),
        )

        # Enable rippling so the issuer's USD can move between holders
        print("Setting up tutorial: 2/5", end="\r")
        await submit_and_wait(
            AccountSet(
                account=issuer.address,
                set_flag=AccountSetAsfFlag.ASF_DEFAULT_RIPPLE,
            ),
            client,
            issuer,
        )

        # Market maker and receiver trust the issuer's USD
        print("Setting up tutorial: 3/5", end="\r")
        await asyncio.gather(
            submit_and_wait(
                TrustSet(
                    account=market_maker.address,
                    limit_amount=IssuedCurrencyAmount(
                        currency=CURRENCY,
                        issuer=issuer.address,
                        value="1000000",
                    ),
                ),
                client,
                market_maker,
            ),
            submit_and_wait(
                TrustSet(
                    account=receiver.address,
                    limit_amount=IssuedCurrencyAmount(
                        currency=CURRENCY,
                        issuer=issuer.address,
                        value="1000000",
                    ),
                ),
                client,
                receiver,
            ),
        )

        # Issue USD to the market maker so it has inventory to sell
        print("Setting up tutorial: 4/5", end="\r")
        await submit_and_wait(
            Payment(
                account=issuer.address,
                destination=market_maker.address,
                amount=IssuedCurrencyAmount(
                    currency=CURRENCY,
                    issuer=issuer.address,
                    value="100000",
                ),
            ),
            client,
            issuer,
        )

        # Post an offer providing XRP -> USD liquidity (4 USD per XRP)
        print("Setting up tutorial: 5/5", end="\r")
        await submit_and_wait(
            OfferCreate(
                account=market_maker.address,
                taker_gets=IssuedCurrencyAmount(
                    currency=CURRENCY,
                    issuer=issuer.address,
                    value="10000",
                ),
                taker_pays=xrp_to_drops(2500),
            ),
            client,
            market_maker,
        )

        setup_data = {
            "description": (
                "Auto-generated by cross_currency_setup.py. Stores XRPL account "
                "info for the cross-currency payment tutorial."
            ),
            "issuer_address": issuer.address,
            "currency": CURRENCY,
            "sender": {"address": sender.address, "seed": sender.seed},
            "receiver": {"address": receiver.address, "seed": receiver.seed},
        }
        with open("cross_currency_setup.json", "w") as f:
            json.dump(setup_data, f, indent=2)


asyncio.run(main())
