# Setup script for sponsored fees and reserves tutorials

import asyncio
import json
import sys

from xrpl.asyncio.clients import AsyncWebsocketClient
from xrpl.asyncio.transaction import submit_and_wait
from xrpl.asyncio.wallet import generate_faucet_wallet
from xrpl.models import (
    MPTokenIssuanceCreate,
    MPTokenIssuanceCreateFlag,
)

WSS_URL = "wss://s.devnet.rippletest.net:51233"


async def main():
    async with AsyncWebsocketClient(WSS_URL) as client:
        print("Setting up tutorial: 0/2", end="\r")

        # Create and fund the MPT issuer
        issuer = await generate_faucet_wallet(client)

        print("Setting up tutorial: 1/2", end="\r")

        # Create the MPT issuance the tutorials authorize with sponsorship
        mpt_create_tx = MPTokenIssuanceCreate(
            account=issuer.address,
            maximum_amount="1000000000000",
            asset_scale=2,
            transfer_fee=0,
            flags=(
                MPTokenIssuanceCreateFlag.TF_MPT_CAN_TRANSFER
                | MPTokenIssuanceCreateFlag.TF_MPT_CAN_LOCK
            ),
        )
        response = await submit_and_wait(mpt_create_tx, client, issuer)
        if response.result["meta"]["TransactionResult"] != "tesSUCCESS":
            result_code = response.result["meta"]["TransactionResult"]
            print(f"Error creating MPT issuance: {result_code}")
            sys.exit(1)

        mpt_issuance_id = response.result["meta"]["mpt_issuance_id"]

        print("Setting up tutorial: 2/2", end="\r")

        # Write the data the tutorials need
        setup_data = {
            "description": "This file is auto-generated by "
            "sponsored_fees_and_reserves_setup.py. It stores XRPL account info for "
            "use in sponsored fees and reserves tutorials.",
            "issuer": {
                "address": issuer.address,
                "seed": issuer.seed,
            },
            "mpt_issuance_id": mpt_issuance_id,
        }

        with open("sponsored_fees_and_reserves_setup.json", "w") as f:
            json.dump(setup_data, f, indent=2)


# Allow running this file directly: `python sponsored_fees_and_reserves_setup.py`
if __name__ == "__main__":
    asyncio.run(main())
