import xrpl from 'xrpl'
import fs from 'fs'
import { fileURLToPath } from 'url'

const currencyCode = 'FOO'
const TOTAL_STEPS = 4

export async function setup() {
  process.stdout.write(`Setting up tutorial: 0/${TOTAL_STEPS}\r`)

  const client = new xrpl.Client('wss://s.altnet.rippletest.net:51233')
  await client.connect()

  // Fund issuer, sender, and receiver wallets from the Testnet faucet.
  const [
    { wallet: issuer },
    { wallet: sender },
    { wallet: receiver }
  ] = await Promise.all([
    client.fundWallet(),
    client.fundWallet(),
    client.fundWallet()
  ])

  process.stdout.write(`Setting up tutorial: 1/${TOTAL_STEPS}\r`)

  // Enable Default Ripple on the issuer so the token can ripple through the
  // issuer's trust lines when holders send it between each other.
  const accountSetResponse = await client.submitAndWait({
    TransactionType: 'AccountSet',
    Account: issuer.address,
    SetFlag: xrpl.AccountSetAsfFlags.asfDefaultRipple
  }, { wallet: issuer, autofill: true })

  if (accountSetResponse.result.meta?.TransactionResult !== 'tesSUCCESS') {
    await client.disconnect()
    throw new Error(`AccountSet failed: ${accountSetResponse.result.meta?.TransactionResult}`)
  }

  process.stdout.write(`Setting up tutorial: 2/${TOTAL_STEPS}\r`)

  // Create a trust line from the sender to the issuer so the sender can hold the token.
  const senderTrustResponse = await client.submitAndWait({
    TransactionType: 'TrustSet',
    Account: sender.address,
    LimitAmount: {
      currency: currencyCode,
      issuer: issuer.address,
      value: '1000000000'
    }
  }, { wallet: sender, autofill: true })

  if (senderTrustResponse.result.meta?.TransactionResult !== 'tesSUCCESS') {
    await client.disconnect()
    throw new Error(`Sender TrustSet failed: ${senderTrustResponse.result.meta?.TransactionResult}`)
  }

  process.stdout.write(`Setting up tutorial: 3/${TOTAL_STEPS}\r`)

  // Issue the token from the issuer to the sender so the sender has a balance to send.
  const issueResponse = await client.submitAndWait({
    TransactionType: 'Payment',
    Account: issuer.address,
    Destination: sender.address,
    Amount: {
      currency: currencyCode,
      issuer: issuer.address,
      value: '1000'
    }
  }, { wallet: issuer, autofill: true })

  if (issueResponse.result.meta?.TransactionResult !== 'tesSUCCESS') {
    await client.disconnect()
    throw new Error(`Issuer Payment failed: ${issueResponse.result.meta?.TransactionResult}`)
  }

  process.stdout.write(`Setting up tutorial: 4/${TOTAL_STEPS}\r`)

  // Write setup data to JSON file.
  const setupData = {
    description: 'This file is auto-generated by sendTrustLineTokenSetup.js. It stores XRPL account info for use in the Send a Trust Line Token tutorial.',
    issuer: {
      address: issuer.address,
      seed: issuer.seed
    },
    sender: {
      address: sender.address,
      seed: sender.seed
    },
    receiver: {
      address: receiver.address,
      seed: receiver.seed
    }
  }

  fs.writeFileSync('sendTrustLineTokenSetup.json', JSON.stringify(setupData, null, 2))

  process.stdout.write('Setting up tutorial: Complete!\n')

  await client.disconnect()
}

// Allow running this file directly: `node sendTrustLineTokenSetup.js`
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await setup()
}
