import xrpl from 'xrpl'
import { stringToHex } from '@xrplf/isomorphic/dist/utils/index.js'
import fs from 'fs'

// Get issuer wallet and define constants -------------------------------------
const client = new xrpl.Client('wss://s.altnet.rippletest.net:51233')
await client.connect()
console.log('Getting a new account from the faucet.')
const { wallet } = await client.fundWallet()
console.log(`Account funded:
  Address: ${wallet.address}
  Seed: ${wallet.seed}
`)

const issuerAddress = wallet.address // Can also use a third-party issuer
const credentialType = stringToHex("my-credential")

// Create a domain ------------------------------------------------------------
const pDomainSet = {
  TransactionType: "PermissionedDomainSet",
  Account: wallet.address,
  AcceptedCredentials: [
    {
      Credential: {
        Issuer: issuerAddress,
        CredentialType: credentialType
      }
    }
  ]
}

console.log('Submitting transaction', JSON.stringify(pDomainSet, null, 2))
const response = await client.submitAndWait(pDomainSet, { wallet, autofill: true})
console.log(response)
const resultCode = response.result.meta.TransactionResult
if (resultCode !== 'tesSUCCESS') {
  console.error(`PermissionedDomainSet failed with code ${resultCode}`)
  client.disconnect()
  process.exit(2)
}

console.log('Successfully created permissioned domain.')

// Find Domain ID in metadata -------------------------------------------------
let domainID
for (const modifiedNode of response.result.meta.AffectedNodes) {
  if (modifiedNode.CreatedNode?.LedgerEntryType === 'PermissionedDomain') {
    domainID = modifiedNode.CreatedNode.LedgerIndex
    break
  }
}
if (!domainID) {
  console.error("Couldn't find a created PermissionedDomain in transaction "+
    "metadata. This is not typical.")
  client.disconnect()
  process.exit(3)
}
console.log('Domain ID of created domain:', domainID)

client.disconnect()

// Save config for other scripts ----------------------------------------------
const configData = {
  description: "This file is auto-generated by create-domain.js. "+
    "It stores account and domain info for the other tutorial scripts.",
  owner: {
    address: wallet.address,
    seed: wallet.seed
  },
  issuer_address: issuerAddress,
  domain_id: domainID
}
fs.writeFileSync('setup.json', JSON.stringify(configData, null, 2))
