import asyncio
import json

from xrpl.asyncio.clients import AsyncWebsocketClient
from xrpl.asyncio.transaction import submit_and_wait
from xrpl.asyncio.wallet import generate_faucet_wallet
from xrpl.models.amounts import IssuedCurrencyAmount
from xrpl.models.transactions import AccountSet, Payment, TrustSet
from xrpl.models.transactions.account_set import AccountSetAsfFlag

WSS_URL = "wss://s.altnet.rippletest.net:51233"
CURRENCY_CODE = "FOO"
TOTAL_STEPS = 4


async def main():
    async with AsyncWebsocketClient(WSS_URL) as client:
        print(f"Setting up tutorial: 0/{TOTAL_STEPS}", end="\r")

        # Fund issuer, sender, and receiver wallets from the Testnet faucet in parallel.
        issuer, sender, receiver = await asyncio.gather(
            generate_faucet_wallet(client),
            generate_faucet_wallet(client),
            generate_faucet_wallet(client),
        )

        print(f"Setting up tutorial: 1/{TOTAL_STEPS}", end="\r")

        # Enable Default Ripple on the issuer so holders can send
        # the token to each other.
        account_set_response = await submit_and_wait(
            AccountSet(
                account=issuer.address,
                set_flag=AccountSetAsfFlag.ASF_DEFAULT_RIPPLE,
            ),
            client,
            issuer,
        )
        result_code = account_set_response.result["meta"]["TransactionResult"]
        if result_code != "tesSUCCESS":
            raise RuntimeError(f"AccountSet failed: {result_code}")

        print(f"Setting up tutorial: 2/{TOTAL_STEPS}", end="\r")

        # Create a trust line from the sender to the issuer so the sender can hold the token.
        sender_trust_response = await submit_and_wait(
            TrustSet(
                account=sender.address,
                limit_amount=IssuedCurrencyAmount(
                    currency=CURRENCY_CODE,
                    issuer=issuer.address,
                    value="1000000000",
                ),
            ),
            client,
            sender,
        )
        result_code = sender_trust_response.result["meta"]["TransactionResult"]
        if result_code != "tesSUCCESS":
            raise RuntimeError(f"Sender TrustSet failed: {result_code}")

        print(f"Setting up tutorial: 3/{TOTAL_STEPS}", end="\r")

        # Issue the token from the issuer to the sender so the sender has a balance to send.
        issue_response = await submit_and_wait(
            Payment(
                account=issuer.address,
                destination=sender.address,
                amount=IssuedCurrencyAmount(
                    currency=CURRENCY_CODE,
                    issuer=issuer.address,
                    value="1000",
                ),
            ),
            client,
            issuer,
        )
        result_code = issue_response.result["meta"]["TransactionResult"]
        if result_code != "tesSUCCESS":
            raise RuntimeError(f"Issuer Payment failed: {result_code}")

        print(f"Setting up tutorial: 4/{TOTAL_STEPS}", end="\r")

        # Write setup data to JSON file.
        setup_data = {
            "description": "This file is auto-generated by send_trust_line_token_setup.py. It stores XRPL account info for use in the Send a Trust Line Token tutorial.",
            "issuer": {
                "address": issuer.address,
                "seed": issuer.seed,
            },
            "sender": {
                "address": sender.address,
                "seed": sender.seed,
            },
            "receiver": {
                "address": receiver.address,
                "seed": receiver.seed,
            },
        }

        with open("send_trust_line_token_setup.json", "w") as f:
            json.dump(setup_data, f, indent=2)

        print("Setting up tutorial: Complete!")


if __name__ == "__main__":
    asyncio.run(main())
